_target_: src.models.covflow_module.CovFlowLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.covariateflow_net.CovariateFlow
  num_coupling_layers: 6
  img_size: [3,28,28]
  import_samples: 8 
  train_set: null

alpha: 1.0


# compile model for faster training with pytorch 2.0
compile: false
