_target_: src.models.normflow_module.NormalizingFlowLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.normflow_multiscale_net.NormFlowMultiScaleNet
  num_blocks: 4
  c_hidden_1: 16
  c_hidden_2: 48
  c_hidden_3: 32
  c_hidden_4: 64

# compile model for faster training with pytorch 2.0
compile: false

import_samples: 8