_target_: src.models.normflow_module.NormalizingFlowLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.normalizing_flow_net.NormFlowNet
  use_vardeq: true
  num_blocks: 8
  c_hidden: 32

# compile model for faster training with pytorch 2.0
compile: false

import_samples: 8

sample_dir: ${paths.sample_dir}/NormFlowNet