_target_: src.models.realnvp_module.RealNVPLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

criterion:
  _target_: src.models.components.loss_functions.losses.RealNVPLoss

net:
  _target_: src.models.components.realnvp_net.RealNVP
  img_size: 32 
  in_channels: 1
  num_scales: 2
  mid_channels: 64
  num_blocks: 8
  alpha: 1
  no_wandb: true
  typicality: false
  


# compile model for faster training with pytorch 2.0
compile: false
